title: BK's 
author: BK
email: brian@ctkeane.com
description: > # this means to ignore newlines until "baseurl:"
  Trying out the blog features on Github

# social links
twitter_username: bckeane
github_username:  bckeane

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima 
